# Site settings
title: Dr. Minseok Song
email: mssong@postech.ac.kr
description: Academic webpage of Dr. Minseok Song
repository: "minseoksong.github.io"
baseurl: ""
url: https://minseoksong.github.io


# Google analytics ID: Remove or use your own!
#google_analytics: UA-167467135-1
google_analytics_4: G-7SBTDX9PW0
#google_tag_manager: GTM-TZ9Z7HZ

# Footer info
affiliation: >
    Minseok Song, Ph.D.<br/>
    Mueunje Professor<br/>
    <a href="http://ime.postech.ac.kr" target="_blank">Department of Industrial & Management Engineering</a><br/>
    <a href="http://www.postech.ac.kr" target="_blank">Pohang University of Science and Technology</a>

location: >
  Engineering Building #4-223<br/>
  Pohang University of Science and Technology<br/>
  77 Cheongam-Ro. Nam-Gu. <br/>
  Pohang. Gyeongbuk. Korea 37673


contact: >
    <a href="mailto:mssong@postech.ac.kr" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact via email</a> <br/>
    <i class="fa fa-github fa-1x"></i> +82 (0) 54 279 2376</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: talks
# - name: research
# - name: software
# - name: team
# - name: teaching

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Minseok
  first_name: [Song]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
